### ISSUE TITLE
Just to say thanks!.

### ISSUE THREAD

**Issue by coforfe** [hkarp1/messy.cats#9]
Hi,

I took note of this package when you first released, but today I had the opportunity to use it `cat_match()`.
I got with your function much more than what I tried before with another convoluted ways.

So, thanks for writting and sharing this!.
Carlos.

**Comment by coforfe** [comment]
Thanks again.

**Comment by abhennessy99** [comment]
Hey Carlos,

This makes me super happy to hear because we started working on cat_match just to solve some problems in my research and avoid convoluted solutions. I'm super glad you found a good use for the function
